apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "expname"
  namespace: user-namespace 
spec:
  predictor:
    serviceAccountName: kserve-minio-secret
    sklearn:
      protocolVersion: "v2"
      storageUri: "s3://mlflow/exp-id/run-id/artifacts/model"
