apiVersion: "sparkoperator.hpe.com/v1beta2"
kind: SparkApplication
metadata:
  name: spark-etl-{{ts_nodash|replace("T", "")}}
spec:
  sparkConf:
    spark.driver.cores: "2"
    spark.executor.cores: "2"
    spark.driver.memory: "1000M"
    spark.executor.memory: "1000M"
    spark.ssl.enabled: "false"
    spark.dynamicAllocation.enabled: "true"
    spark.dynamicAllocation.shuffleTracking.enabled: "true"
    spark.dynamicAllocation.minExecutors: "1"
    spark.dynamicAllocation.maxExecutors: "4"
    spark.sql.extensions: "io.delta.sql.DeltaSparkSessionExtension"
    spark.sql.catalog.spark_catalog: "org.apache.spark.sql.delta.catalog.DeltaCatalog"
    spark.executor.extraJavaOptions: "-Dcom.amazonaws.sdk.disableCertChecking=true"
    spark.driver.extraJavaOptions: "-Dcom.amazonaws.sdk.disableCertChecking=true"
    spark.hadoop.fs.s3a.path.style.access: "true"
    spark.hadoop.fs.s3a.impl: "org.apache.hadoop.fs.s3a.S3AFileSystem"
    spark.hadoop.fs.s3a.connection.ssl.enabled: "false"
    spark.hadoop.fs.s3a.access.key: "PO93KAAP2YTG4RHMG499FENAFWYUH9Q91XOJYQ6UNY4R0XUVY35A53L47"
    spark.hadoop.fs.s3a.secret.key: "UV0H7MFJI96MCFY03IMD9X6ZT8H43B3GDS8SXGA4Z7FH0QT2DSZV3ZCKTHS93Z"
    spark.hadoop.fs.s3a.endpoint: "https://54.251.141.200:9000"
        spark.kubernetes.driverEnv.PRESTO_ACCESS_TOKEN: "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJwNTdWNHFEVldrTlp6Zkw4Z0h1STNmRHdtTFQ0VjlMN05wWDFMWkdOWjg4In0.eyJleHAiOjE3MDc0NTAzODYsImlhdCI6MTcwNjkzMzM5NiwiYXV0aF90aW1lIjoxNzA2ODQ1NTg2LCJqdGkiOiJlZDJkYzYyYi1hNmJjLTQ3MjUtOGFiYS1mYTBlNTU1YzhiOTAiLCJpc3MiOiJodHRwczovL2tleWNsb2FrLnRydWVwb2MuZXphcGFjLmNvbS9yZWFsbXMvVUEiLCJhdWQiOiJ1YSIsInN1YiI6ImQxYTliNTNjLWEzNGItNDUzNy05YTMzLWNjZjBjZDFjY2VjMSIsInR5cCI6IklEIiwiYXpwIjoidWEiLCJub25jZSI6IklDNzBiV0tGam9GWUJRemQtaXItUjVEU09CTVhpRUQ4c1pnWTBIWjlLRUUiLCJzZXNzaW9uX3N0YXRlIjoiNTdjN2Y0YTAtMTZkMy00MjJhLTkwMmUtNTNhOWZjMDFiZmU4IiwiYXRfaGFzaCI6InFLSVNCaER2anNlc3VSbkpwdTdZWkEiLCJhY3IiOiIwIiwic2lkIjoiNTdjN2Y0YTAtMTZkMy00MjJhLTkwMmUtNTNhOWZjMDFiZmU4IiwidWlkIjoiNjAwMCIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZ2lkIjoiNTAwNSIsIm5hbWUiOiJlemFkbWluIHRlc3QiLCJncm91cHMiOlsidWEtZW5hYmxlZCIsIm9mZmxpbmVfYWNjZXNzIiwiYWRtaW4iLCJ1bWFfYXV0aG9yaXphdGlvbiIsImRlZmF1bHQtcm9sZXMtdWEiXSwicHJlZmVycmVkX3VzZXJuYW1lIjoiZXphZG1pbiIsImdpdmVuX25hbWUiOiJlemFkbWluIiwicG9zaXhfdXNlcm5hbWUiOiJlemFkbWluIiwiZmFtaWx5X25hbWUiOiJ0ZXN0IiwiZW1haWwiOiJlemFkbWluQGV6YXBhYy5jb20ifQ.BoL7bzmuR5FKXd8mq-3jraJS4gz51YVO7NXzpXqNqpNcWHIhfctfGKN3y_n6ZXB-_GrWZXi77_wMuGOG8vS9JHi4YjQNDmZ_rJUv18lQc9-FAMz_CyOVCJcOucvfLirCJ07_nBaLJgoYrHXmSWPKVDas5PEzWf3YVHCMKsGWmnBx26u5xME73bpUGWeg38um-JbtCFlO-ClRRCx0xeze_ode2HlHnXBn54hKfss7C5uwqyQQ4sdBL4l6VtJ0OhiG0E9Ll1BOZ7l8E8Nkx_lw97FitUupp1CnpSNoxsdAt-p4m-QnyfuZ8A3lOGxhTmEpQS5PlBP4_vIWEyQ6Vd2MXA"
    spark.executorEnv.PRESTO_ACCESS_TOKEN: "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJwNTdWNHFEVldrTlp6Zkw4Z0h1STNmRHdtTFQ0VjlMN05wWDFMWkdOWjg4In0.eyJleHAiOjE3MDc0NTAzODYsImlhdCI6MTcwNjkzMzM5NiwiYXV0aF90aW1lIjoxNzA2ODQ1NTg2LCJqdGkiOiJlZDJkYzYyYi1hNmJjLTQ3MjUtOGFiYS1mYTBlNTU1YzhiOTAiLCJpc3MiOiJodHRwczovL2tleWNsb2FrLnRydWVwb2MuZXphcGFjLmNvbS9yZWFsbXMvVUEiLCJhdWQiOiJ1YSIsInN1YiI6ImQxYTliNTNjLWEzNGItNDUzNy05YTMzLWNjZjBjZDFjY2VjMSIsInR5cCI6IklEIiwiYXpwIjoidWEiLCJub25jZSI6IklDNzBiV0tGam9GWUJRemQtaXItUjVEU09CTVhpRUQ4c1pnWTBIWjlLRUUiLCJzZXNzaW9uX3N0YXRlIjoiNTdjN2Y0YTAtMTZkMy00MjJhLTkwMmUtNTNhOWZjMDFiZmU4IiwiYXRfaGFzaCI6InFLSVNCaER2anNlc3VSbkpwdTdZWkEiLCJhY3IiOiIwIiwic2lkIjoiNTdjN2Y0YTAtMTZkMy00MjJhLTkwMmUtNTNhOWZjMDFiZmU4IiwidWlkIjoiNjAwMCIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZ2lkIjoiNTAwNSIsIm5hbWUiOiJlemFkbWluIHRlc3QiLCJncm91cHMiOlsidWEtZW5hYmxlZCIsIm9mZmxpbmVfYWNjZXNzIiwiYWRtaW4iLCJ1bWFfYXV0aG9yaXphdGlvbiIsImRlZmF1bHQtcm9sZXMtdWEiXSwicHJlZmVycmVkX3VzZXJuYW1lIjoiZXphZG1pbiIsImdpdmVuX25hbWUiOiJlemFkbWluIiwicG9zaXhfdXNlcm5hbWUiOiJlemFkbWluIiwiZmFtaWx5X25hbWUiOiJ0ZXN0IiwiZW1haWwiOiJlemFkbWluQGV6YXBhYy5jb20ifQ.BoL7bzmuR5FKXd8mq-3jraJS4gz51YVO7NXzpXqNqpNcWHIhfctfGKN3y_n6ZXB-_GrWZXi77_wMuGOG8vS9JHi4YjQNDmZ_rJUv18lQc9-FAMz_CyOVCJcOucvfLirCJ07_nBaLJgoYrHXmSWPKVDas5PEzWf3YVHCMKsGWmnBx26u5xME73bpUGWeg38um-JbtCFlO-ClRRCx0xeze_ode2HlHnXBn54hKfss7C5uwqyQQ4sdBL4l6VtJ0OhiG0E9Ll1BOZ7l8E8Nkx_lw97FitUupp1CnpSNoxsdAt-p4m-QnyfuZ8A3lOGxhTmEpQS5PlBP4_vIWEyQ6Vd2MXA"
    spark.kubernetes.container.image: "gcr.io/mapr-252711/spark-3.4.0:v3.4.0"
    
  type: Python
  sparkVersion: 3.4.0
  mode: cluster
  image: "gcr.io/mapr-252711/spark-3.4.0:v3.4.0"
  imagePullPolicy: Always
  mainApplicationFile: "local:///mnt/shared/Toh/Framework.py"
  restartPolicy:
    type: Never
  imagePullSecrets:
    - imagepull
  driver:
    cores: 2
    coreLimit: "2000m"
    memory: "1000M"
    labels:
      version: 3.4.0
    env:
      - name: STREM_NM
        value: "{{ params.STREM_NM }}"

  executor:
    cores: 2
    coreLimit: "2000m"
    memory: "1000M"
    labels:
      version: 3.4.0
